### PR TITLE
Add recipe for Raspberry Pi 4

### PR DESCRIPTION
**Pull request by andhe**
This adds a basic recipe for the RPi4.

(For unknown reasons the serial console output gets garbled once the kernel starts up, but the system starts and runs successfully.)

### CODE REVIEW

**Comment by wartstew** [comment]
Hi andhe:

I just tried your recipe for Raspberry Pi 4 on real hardware.  The firmware booted but U-boot started looking for a network to boot from (pxeboot/bootp).  I'm guessing it didn't find it's root file system.  It DID get an IP from my DHCP server at least.  I verified that the UUID matched between the root partition you have on your "cmdline" with what is on the actual partition.  Also once U-boot timed out to a "U-Boot>" prompt, my USB keyboard was not detected so I could not issue commands without possibly connecting up a serial device to the proper I/O pins.

Looking forward for this to work as it looks like a simplified implementation to boot Debian.

**Comment by d4s** [comment]
I have a working recipe based on Apertis (which is derivative from Debian).

Please let me to return from vacations next week to proceed with this MR.

At the first sight the proposed recipe in MR have some issues -- I'll check it later with real HW test.
For example: U-Boot **must** have rpi64 target -- this allows to boot RPi3 **and** RPi4 with the single image. I have all needed patches and will  push those changes to Debian's U-boot package.

**Comment by wartstew** [comment]
Thanks for your work and reply.

I proceeded with starting over using debootstrap then adding the Ubuntu firmware/bootloader to it to get a booting debian on my RPI-4. I discovered your image runs Sid (unstable), and my application would prefer Buster (Stable) anyway. In fact I just booted and still using your 5.7.x kernel + modules and I get no sound devices (either analog or HDMI) for some reason so shortly I will also try Ubuntu's kernel (or possibly even Manjaro's) and see if that works any better.

Also your image booted into an image that was not as configured as I'm accustomed to debootstrap leaving for me (are you using a simpler "variant" mode?), so it left me struggling through getting networking and further configuration without even a text editor, or "net-tools" installed! It also did the combined /bin /sbin /lib with /usr/bin /usr/sbin /usr/lib mode that I don't think is too appropriate for the "full sized" installation I'm planning. Just letting you know in case all this is not what you are planning either.

Thanks for the experience anyway as this was my first introduction to Debian "recipes", which I thought was interesting how it then ran it in a qemu instance, which I did not know if I could log into and monitor it's actions/progress or not. (I've never used qemu either). In fact it has been years since I ever played around with u-boot as well, so I'm pretty "over my head" with most of this, but did get my Debian Arm64 "Buster" running on my RPI-4 at least, just need to get sound. I also don't think it is finding the Wifi/BT either (I don't care for this application), so might look into why not as well.

     On Wednesday, July 15, 2020, 03:27:53 AM MDT, Denis Pynkin <notifications@github.com> wrote:  
 
 


I have a working recipe based on Apertis (which is derivative from Debian).

Please let me to return from vacations next week to proceed with this MR.

At the first sight the proposed recipe in MR have some issues -- I'll check it later with real HW test.
For example: U-Boot must have rpi64 target -- this allows to boot RPi3 and RPi4 with the single image. I have all needed patches and will push those changes to Debian's U-boot package.

**Comment by d4s** [comment]
Just drop the link to bug&MR with unified U-Boot for RPi 3 and 4: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966078

**Comment by andhe** [comment]
Hi @d4s and thanks for looking into this MR.

> At the first sight the proposed recipe in MR have some issues -- I'll check it later with real HW test.

Works for me (on real hardware). If you spot any issues, then please just mention what/where.

> For example: U-Boot **must** have rpi64 target -- this allows to boot RPi3 **and** RPi4 with the single image. I have all needed patches and will push those changes to Debian's U-boot package.

There has previously not been any interest in unifying the rpi3b and rpi3b+ recipes in the debos-recipes repo, so I find it quite peculiar that unifying rpi3 and rpi4 is suddently a blocker....

**Comment by d4s** [comment]
@andhe sorry for a long silence. Please check https://github.com/go-debos/debos-recipes/pull/19
I want to know your opinion about it. Tested on RPi 3 and 4.

**Comment by andhe** [comment]
This is obsolete by #19 so closing....

**Pull request closed without merging**
